GoogleCloudPlatform/flink-on-k8s-operator

config/samples/flinkoperator_v1alpha1_flinkjobcluster.yaml, config/samples/flinkoperator_v1alpha1_flinksessioncluster.yaml, controllers/flinkcluster_converter.go
The limits will be used by the containers to set the default Java heap
size for JM/TM processes.
=> Pass resource limits to JM/TM containers through Downward API

api/v1alpha1/flinkcluster_types.go, config/rbac/role.yaml, controllers/flinkcluster_controller.go, controllers/flinkcluster_converter.go, controllers/flinkcluster_observer.go, controllers/flinkcluster_reconciler.go, controllers/flinkcluster_updater.go
Job status could be marked as Running when the pod is still pending for
being scheduled, this caused we mark FlinkCluster status as Running when
it is still creating.
Fix #30
=> Check job pod status in addition to job status to update CR status

controllers/flinkcluster_controller.go
Reconciliation event should be immediately rescheduled if a controller enters an error condition and returns an error in the reconcile method.
=> Re-queue the reconcile after reconciliation failed.

controllers/flinkcluster_controller.go, controllers/flinkcluster_converter.go, controllers/flinkcluster_converter_test.go, controllers/flinkcluster_reconciler.go
After the job finishes, the cluster will transit into Stopping state
and keep in that state for 5 mins, then start deleting cluster
resources.
=> Delay deleting cluster resources by 5 mins after the job finishes

controllers/flinkcluster_util.go
It seems that we can't parse the time format with time zone offset. RFC3339 layout should be applied when reading as well as when writing savepoint time.
--------------------------------------------
2019-10-24T09:57:27.190+0900	INFO	controllers.FlinkCluster	---------- 4. Take actions ----------	{"cluster": "elan/fcs"}
2019-10-24T09:57:27.190+0900	INFO	controllers.FlinkCluster	Deployment already exists, no action	{"cluster": "elan/fcs", "component": "JobManager"}
2019-10-24T09:57:27.190+0900	INFO	controllers.FlinkCluster	JobManager service already exists, no action	{"cluster": "elan/fcs"}
2019-10-24T09:57:27.190+0900	INFO	controllers.FlinkCluster	Deployment already exists, no action	{"cluster": "elan/fcs", "component": "TaskManager"}
E1024 09:57:27.190395   43338 runtime.go:67] Observed a …
=> Fix to parse time format of last savepoint that includes time zone offset

controllers/flinkcluster_converter_test.go
Changed resource names to the constants defined in types.go.
Some tests require you to use Resources.Limits.Memory(), which requires resources should be defined with the constant names.
https://github.com/kubernetes/api/blob/master/core/v1/types.go#L4557
=> Fix resource keys in tests

api/v1alpha1/flinkcluster_default.go, api/v1alpha1/flinkcluster_default_test.go, api/v1alpha1/flinkcluster_types.go, api/v1alpha1/flinkcluster_validate.go, api/v1alpha1/flinkcluster_validate_test.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster_converter.go, controllers/flinkcluster_converter_test.go, docs/crd.md
In order to run the Flink processes stably and avoid OOM kill in a container environment, appropriate off-heap space is required. Since jobmanager.heap.size and taskmanager.heap.size are the properties that determines the size of the Flink JVM heap, it is needed to calculate them based on the memory resource limit of the pod like Flink resource manager does for yarn cluster.
(https://ci.apache.org/projects/flink/flink-docs-stable/ops/config.html#resource-manager)
And since the files mounted with ConfigMap are read-only, it is not possible to modify the flink-conf.yaml in the entrypoint script with environment variables inside the container.
Memory related configurations would be changed in future release.
* Note: related issues
- https://jira.apache.org/jira/browse/FLINK-13980
- …
=> Calculate Flink JVM heap size

README.md, api/v1alpha1/flinkcluster_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, config/samples/flinkoperator_v1alpha1_flinkjobcluster.yaml, config/samples/flinkoperator_v1alpha1_remotejobjar.yaml, controllers/flinkcluster_converter.go, controllers/flinkcluster_converter_test.go, docs/crd.md
A typical use case could be use an init container to download a remote
jar to a local path which is referenced by the jarFile field.
=> Support initContainers in JobSpec

controllers/flinkcluster_converter.go, controllers/flinkcluster_observer.go, controllers/flinkcluster_reconciler.go
Unexpected running jobs typically happens when the job client timed
out and exited but the job submission was actually successful. Then
when retrying to submit the job, it needs to cancel the existing one
first.
Fix #88
=> Cancel running jobs before submitting a job

api/v1alpha1/flinkcluster_default.go, api/v1alpha1/flinkcluster_default_test.go, api/v1alpha1/flinkcluster_types.go, api/v1alpha1/flinkcluster_validate.go, api/v1alpha1/flinkcluster_validate_test.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster_converter.go, controllers/flinkcluster_converter_test.go, controllers/flinkcluster_reconciler.go, docs/crd.md
Due to the stateful nature of Flink jobs, job restart is better to be initiated by the operator based on restart policy.
=> Disable restarting failed jobs at K8S job level

Makefile, config/default/kustomization.yaml
Added undeploy-crd and undeploy-controller.
Since the controller depends on the CRD, it seems impossible to separate the deployment process for the CRD and the controller. And CRD deploy action already exists as "install"
=> Separate undeploy process for controller and CRD in Makefile

Makefile, config/default/kustomization.yaml, config/default/kustomizeconfig.yaml, config/default/webhook_namespace_selector_patch.yaml, docs/user_guide.md
Currently, Makefile supports only one operator deployment on one k8s cluster. It seems that the following template generation feature is required to deploy multiple operators.
- Avoid duplicate cluster-scoped resource names
- Support selector to prevent admission webhook call interference (namespaceSelector is used in this PR)
To do this, in this PR build-overlay action is added to the Makefile and webhook patch is added to kustomize config.
Operators can be deployed like:
```bash
make deploy  WATCH_NAMESPACE=dev RESOURCE_PREFIX=dev-
```
=> Support multiple operator deployment

helm-chart/flink-operator/README.md
The FlnkCluster CRD version defined in the link in the document is v1alpha1, which should be changed to where v1beta1 is defined.
Related issue: https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/207
=> Update helm chart install guide

docs/user_guide.md
Resolve #214 
Actually we can use `--generator=job/v1` to replace ` --generator=run-pod/v1 ` as well, but this has deprecated and will be removed in a future version
```
kubectl run --generator=job/v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
```
Use job manifest instead.
=> Use Job with restartPolicy=Never as job-submitter type in examples

controllers/flinkcluster_submit_job_script.go
=> Exit with non-zero code when job failed or was canceled

helm-chart/flink-operator/Chart.yaml
I got an exception when trying to push this charts to the my server.
It show me that the chart version shoud use the Semantic Versioning. If the version is not "Semantic Versioning"， the chart server will not recognize it.
Semantic version Guide: https://semver.org/
=> Using Semantic Versioning for Chart version.

controllers/flinkcluster_submit_job_script.go
It seems we need to check active jobs first to decide job state.
It would be better if we improved it later to determine the state with the submitted job ID. 
#231
=> Check active job first to decide job state

api/v1beta1/flinkcluster_types.go, api/v1beta1/flinkcluster_validate.go, controllers/flinkcluster_converter.go, controllers/flinkcluster_observer.go, controllers/flinkcluster_reconciler.go, controllers/flinkcluster_updater.go, controllers/flinkcluster_util.go
Currently when job cancellation is requested, savepoint creation and job cancellation is processed sequentially in the same iteration. In this PR, savepoint is triggered in the first iteration, then the job is stopped and deleted in the next iteration where the savepoint is completed.
Job cancellation status sample:
```
Status:
...
...
Control:
Name:            job-cancel
State:           Succeeded
Update Time:     2020-05-08T01:28:07+09:00
Savepoint:
Job ID:          944ff9266de15b2bc1d790b7341e5b8f
State:           Succeeded
Trigger ID:      558d4a49de7754349f776b5f42e613b3
Trigger Reason:  for job-cancel
Trigger Time:    2020-05-08T01:27:46+09:00
State:             Stopped
Events:
Type    Reason              Age   From           Message
----    ------              ----  ---- …
```
=> Cancel job with non-blocking savepoint

api/v1beta1/flinkcluster_types.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster_converter.go, controllers/flinkcluster_converter_test.go, docs/crd.md
To satisfy https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/268 , I want supports which accepts user defined annotations in k8s [PodTemplateSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#podtemplatespec-v1-core). It should be useful to support flexible configurations.
=> Support podTemplateAnnotations which injects custom annotations

api/v1beta1/flinkcluster_types.go, api/v1beta1/zz_generated.deepcopy.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster_converter.go, controllers/flinkcluster_converter_test.go, docs/crd.md
This change adds support for `initContainers` in `jobManager` and `taskManager`. This allows users to initialize the job and task managers if necessary prior to starting.
Can address issue in #234.
=> Add support for initContainers in job and task manager.

api/v1beta1/flinkcluster_types.go, api/v1beta1/flinkcluster_validate.go, controllers/flinkcluster_converter.go, docs/crd.md
Adds `Headless` as a valid enumerated option for the `spec.jobmanager.accessScope` property in the CRD, in order to generate a [headless service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) for the jobmanager.
This is useful when, for example, your pod network is directly routable and you'd like to use `SRV` records (or `A` round-robin) to discover the underlying pod IPs. In this kind of topology, it is possible to avoid ingress completely yet still communicate with the jobmanager from outside the Kubernetes cluster.
Thanks!
=> Add Headless AccessScope to jobmanager service spec

api/v1beta1/flinkcluster_types.go, api/v1beta1/zz_generated.deepcopy.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster_converter.go, controllers/flinkcluster_converter_test.go, docs/crd.md
This new feature is to support EnvFromSource in cluster spec.
Prerequisites：
none
Why this feature:
Currently spec allows defining env vars but not env from source, for configmaps and secrets.
Solution:
In the Spec of FlinkCluster, we introduce a new property, "envFrom", of type []corev1.EnvFromSource.
=> Support for EnvFromSource in cluster spec

examples/beam/with_job_server/beam_job_server.yaml
Current beam_job_server.yaml can not be deployed to K8s 1.16 and above. the major reason is
1. `apps/v1beta` has been deprecated, we need to migrate to `apps/v1`
```
error: unable to recognize "beam_job_server.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
```
2. deployment doesn't have selector which violates deployment spec. 
```
error: error validating "beam_job_server.yaml": error validating data: ValidationError(Deployment.spec): 
missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
```
This PR helps to make it deploy on 1.16+.
=> Support beam job server manifest on 1.16+

api/v1beta1/flinkcluster_default_test.go, api/v1beta1/flinkcluster_types.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, config/samples/flinkoperator_v1beta1_flinkjobcluster.yaml, config/samples/flinkoperator_v1beta1_flinksessioncluster.yaml, controllers/flinkcluster_converter.go, controllers/flinkcluster_converter_test.go, docs/crd.md, docs/user_guide.md
Expose the PodSecurityContext for JobManager, TaskManager, and Job pods in the FlinkClusterSpec.
This lets us run them as the Flink user, as mentioned in https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/312
=> Expose SecurityContext in FlinkClusterSpec

.circleci/release.sh, helm-chart/flink-operator/README.md, helm-chart/flink-operator/templates/flink-operator.yaml, helm-chart/flink-operator/templates/generate-cert.yaml, helm-chart/flink-operator/update_template.sh, helm-chart/flink-operator/values.yaml
Signed-off-by: Yaron Idan <yaronidan@gmail.com>
Closes #348 
I chose to stick with the convention seen in the rest of the chart and move the namespace name and create flag under the `flinkOperatorNamespace` key. 
This choice is a breaking change for anyone using a non-default namespace name, if you think it's too much I can leave both keys in the root level of the values file.
=> add ns create flag

helm-chart/flink-operator/templates/generate-cert.yaml
Fix the issue [356](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/356)
We should make the expire days longer, the default expires days is 30, we change it to 3650.
=> make the webhook expire days longer

controllers/flinkcluster_reconciler.go
* Job recovery bug
When job manager fails and job state falls to `Lost`, job is not properly recovered.
The job is resubmitted, but the previous job ID is not cleared, so it is considered an unexpected job and is canceled. 
* Savepoint bug
Savepoint is not triggered properly.
Resolves #398
=> Fix job recovery and savepoint bug

docs/savepoints_guide.md
Change `FixSavePoint` -> `FixSavepoint` in `savepoints_guide.md` docs.
related issue: https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/395#issuecomment-764472587
=> Fix from savepoint typo in docs

helm-chart/flink-job-cluster/values.yaml
When deploying the chart with default values you see an error like this:
> Helm upgrade failed: failed to create resource: FlinkCluster.flinkoperator.k8s.io "flink-flink-cluster-flink-job-cluster" is invalid: spec.job.parallelism: Invalid value: "null": spec.job.parallelism in body must be of type integer: "null"
Fixing the typo here resolves the issue.
=> Fix a typo in helm-chart/flink-job-cluster default values

helm-chart/flink-job-cluster/README.md
There's a [broken link](https://github.com/marcomicera/flink-on-k8s-operator/blob/master/helm-chart/flink-job-cluster/README.md) to the Flink job cluster Helm Chart guide.
=> Fixed link to job cluster Helm Chart guide
