controllers/flinkcluster_observer.go
Previously when the cluster CR has been deleted, it throws nil pointer error at line 88.
=> Fix nil pointer error

controllers/flinkcluster_converter.go
=> Rename EXTRA_FLINK_PROPERTIES to FLINK_PROPERTIES

docs/crd.md
=> Update CRD doc for TaskManager sidecars

config/rbac/role.yaml, controllers/flinkcluster_controller.go, controllers/flinkcluster_updater.go
=> Add status update events for FlinkCluster CR

controllers/flinkcluster_observer.go, controllers/flinkcluster_updater.go
Allow cluster status to be Running while job status is Pending
=> Separate cluster status and job status

controllers/flinkcluster_controller.go, controllers/flinkcluster_observer.go, controllers/flinkcluster_reconciler.go, controllers/flinkcluster_updater.go, flinkclient/FlinkClient.go, go.mod, go.sum
=> Submit job after Flink API is ready

controllers/flinkcluster_updater.go, controllers/flinkcluster_updater_test.go
=> Fix JM/TM deployment status

api/v1alpha1/flinkcluster_types.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster_reconciler.go, controllers/flinkcluster_updater.go
=> Make status a subresource which could be updated independently

README.md, docs/streaming_test_env_setup.md
=> Add doc on setting up test env for streaming applications

controllers/flinkcluster_converter.go, controllers/flinkcluster_converter_test.go
=> Add liveness probe for JM/TM containers

docs/crd.md, docs/crd_v1alpha1.md
Added afterJobCancelled to cleanupPolicy and fixed typos.
=> Update CRD doc 

helm-chart/flink-operator/templates/flink-operator.yaml, helm-chart/flink-operator/values.yaml
=> Add watchNamespace to helm chart values

api/v1beta1/flinkcluster_types.go, api/v1beta1/flinkcluster_validate.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster_converter.go, controllers/flinkcluster_updater.go, controllers/flinkcluster_updater_test.go, docs/crd.md
add accessScope [NodePort] , for support k8s access service  with NodePort
=> Add jobmananger service support Nodeport

docs/user_guide.md
I installed this operator in minikube on my local machine, and in the way there I noticed some dependencies were not covered by the user guide
=> Added missing installation dependencies

Makefile, config/default/manager_auth_proxy_patch.yaml, controllers/flinkcluster_controller.go, helm-chart/flink-operator/update_template.sh, main.go
Used ctrl.Options to limit watched namespace.
ctrl.Options.namespace allows to cache resources for specific namespace.
And modified Makefile to generate template --watch-namespace enabled.
=> Use ctrl.Options to limit watched namespace and generate template --watch-namespace enabled

controllers/flinkcluster_submit_job_script.go
Add CANCELED status when wait_for_job #194
=> Add CANCELED status when wait_for_job

docs/user_guide.md, examples/prometheus/flink_metric_cluster.yaml, examples/prometheus/pod-monitor.yaml
This PR includes Prometheus monitoring example and updated user doc.
extraPorts and podMonitor CR of Prometheus operator is used for the example.
=> Introduce Prometheus monitoring example

controllers/flinkcluster_submit_job_script.go
ref: https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/252
=> Add restarting job status and handle it as an active job

controllers/flinkcluster_submit_job_script.go
refs: https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/252
=> Skip unknown job state, check it again in the next iteration

README.md, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, docs/developer_guide.md
=> Update k8s dependency to 1.15+ and regenerate CRD

controllers/flinkcluster_submit_job_script.go
ref: https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/252
=> Check the status of "No running jobs" and "No scheduled jobs" and then exit with code 3.

api/v1beta1/flinkcluster_types.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster_converter.go, controllers/flinkcluster_converter_test.go
This PR add  [Resources](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/273) in job template
=> feat: Add resources support for job template  

controllers/flinkcluster_converter.go, controllers/flinkcluster_converter_test.go
I'd neglected to set `EnvFrom` in the job spec
=> Set EnvFrom in Job Spec

docs/beam_guide.md, examples/beam/without_job_server/beam_wordcount_java.yaml
This is related to https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/230
=> feat: Add Direct Runner for Beam Java SDK Example

helm-chart/flink-operator/templates/flink-operator.yaml
This PR add image pull secret and node selector for flink operator deployment.
=> feat: image pull secret and node selector for flink operator deployment.

controllers/flinkcluster_util.go, controllers/flinkcluster_util_test.go, docs/user_guide.md
=> make the cluster domain configurable

api/v1beta1/flinkcluster_types.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster_converter.go, docs/crd.md
=> Add podLabels to JM, TM, Job

helm-chart/flink-operator/templates/flink-operator.yaml
Fixes https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/327
=> Add imagePullPolicy to flink-operator Helm template

api/v1beta1/flinkcluster_types.go, config/crd/bases/flinkoperator.k8s.io_flinkclusters.yaml, controllers/flinkcluster_converter.go, controllers/flinkcluster_converter_test.go, docs/crd.md
support passing service account name to operator definition
=> support service account name

Makefile
Fixes #342 
Also could this be added to Hactoberfest?
=> Fix deploy target not replacing IMG

docs/savepoints_guide.md
Related to [this](https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/issues/344)
=> ISSUE-344 minor doc corrections

helm-chart/flink-operator/templates/flink-operator.yaml
It seems I've let a bug slip buy in previous PR (#348) in it broke the chart. This PR is a minor fix for that.
=> fix image name

helm-chart/flink-operator/templates/flink-cluster-crd.yaml
=> Update Helm chart CRD for PR #379

docs/flink_job_cluster_guide.md
The period was on the wrong side of the bracket :-)
=> Update flink_job_cluster_guide.md to fix broken link
